### ISSUE TITLE
Bug in SendData

### ISSUE THREAD

**Issue by UlixDev** [pozyxLabs/Pozyx-Python-library#10]
When I run the snippet of code
dev_id = NetworkID(2)
data = Data()
data.data = [1,2,43,4]
data.format_data = ['BBBB']
tag.sendData(dev_id, data)

The following traceback pops out 
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pypozyx/core.py", line 423, in sendData
    status &= self.sendTXBufferData(destination)
  File "/usr/local/lib/python2.7/dist-packages/pypozyx/core.py", line 402, in sendTXBufferData
    status = self.regFunction(POZYX_TX_SEND, params, [])
  File "/usr/local/lib/python2.7/dist-packages/pypozyx/pozyx_serial.py", line 163, in regFunction
    s = 'F,%0.2x,%s,%i\r' % (address, params.byte_data, data.byte_size + 1)
**AttributeError: 'list' object has no attribute 'byte_size'**

**I put the line under if/else
if (len(data) == 0):
    s = 'F,%0.2x,%s,%i\r' % (address, params.byte_data, params.byte_size + 1)
else:
    s = 'F,%0.2x,%s,%i\r' % (address, params.byte_data, data.byte_size + 1)**

It seems to work

**Comment by laurentva** [comment]
Hey Ulisse,

It should be fixed now if I commit the issues fixes, [] was changed to Data([]). In the future, you can write Data([1, 2, 43, 4]) as the data format defaults to 'B' for each data element.
