### ISSUE TITLE
Python 2 problem when importing the library

### ISSUE THREAD

**Issue by orestisvaresis** [pozyxLabs/Pozyx-Python-library#49]
I tried installing pypozyx via pip install pypozyx and this installs it for python 3.5 
I then tried pip2 install pypozyx and this is getting the library installed for python 2.7
But when I try to import the library I get the following error.
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/orestis/.local/lib/python2.7/site-packages/pypozyx/__init__.py", line 90, in <module>
    from pypozyx.pozyx_serial import *
  File "/home/orestis/.local/lib/python2.7/site-packages/pypozyx/pozyx_serial.py", line 7, in <module>
    from pypozyx.lib import PozyxLib
  File "/home/orestis/.local/lib/python2.7/site-packages/pypozyx/lib.py", line 925
    def getPositioningData(self, positioning_data: PositioningData):
                                                 ^
SyntaxError: invalid syntax
`

**Comment by laurentva** [comment]
Hi!

This is fixed in release 1.2.1. Please update or run pip2 install "pypozyx==1.2.1"

Kind regards,
