### ISSUE TITLE
Bug in setSelectionOfAnchors

### ISSUE THREAD

**Issue by UlixDev** [pozyxLabs/Pozyx-Python-library#5]
When I execute the snippet of
 n =SingleRegister(how_many)
 setSelectionOfAnchors(POZYX_ANCHOR_SEL_MANUAL, n[0])
The following traceback pops out
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/osboxes/prj/dfw/Pozyx_scripts/meanTAGPositioning.py", line 23, in TAGInit
    tag.tag.setSelectionOfAnchors(POZYX_ANCHOR_SEL_MANUAL, n[0])
  File "/usr/local/lib/python2.7/dist-packages/pypozyx/lib.py", line 1175, in setSelectionOfAnchors
    **params = Data([(mode << 7) + nr_anchors])
TypeError: unsupported operand type(s) for <<: 'instance' and 'int'**

The bug appears both in python2.7 and python3.5 grammar
I think mode should be converted in mode[0]
I did it manually on my installed lib and it worked

**Comment by laurentva** [comment]
Yes, I thought I had all of them but apparently I didn't in setSelectionOfAnchors. Thanks man :)
