### ISSUE TITLE
Bug #3 in setSelectionOfAnchors

### ISSUE THREAD

**Issue by UlixDev** [pozyxLabs/Pozyx-Python-library#7]
When I execute the snippet of code
n = SingleRegister(how_many)
tag.tag.setSelectionOfAnchors(POZYX_ANCHOR_SEL_MANUAL, n)

The following traceback pops out
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/osboxes/prj/dfw/Pozyx_scripts/meanTAGPositioning.py", line 25, in TAGInit
    tag.tag.setSelectionOfAnchors(POZYX_ANCHOR_SEL_MANUAL, n)
  File "/usr/local/lib/python2.7/dist-packages/pypozyx/lib.py", line 1173, in setSelectionOfAnchors
    **0] <= 16, 'setSelectionOfAnchors: num anchors %i not in range 3-16' % nr_anchors
TypeError: %d format: a number is required, not instance**

I think here  % nr_anchors should be corrected in % nr_anchors[0]
Moreover I think that same consideration as in #6 hold

**Comment by laurentva** [comment]
Directly related to #8  , fixed. This is the other stuff I did in there.
