### ISSUE TITLE
Bug in doRanging

### ISSUE THREAD

**Issue by UlixDev** [pozyxLabs/Pozyx-Python-library#9]
When I execute the snippet of code

t = PozyxSerial('/dev/ttyACM0')
Range = DeviceRange()
Id = NetworkID(1)
t.doRanging(Id, Range)

The following traceback pops out

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pypozyx/lib.py", line 1279, in doRanging
    POZYX_DO_RANGING, destination, Data([]), remote_id)
  File "/usr/local/lib/python2.7/dist-packages/pypozyx/core.py", line 116, in useFunction
    status = self.regFunction(function, params, data)
  File "/usr/local/lib/python2.7/dist-packages/pypozyx/pozyx_serial.py", line 162, in regFunction
    params.load_hex_string()
  File "/usr/local/lib/python2.7/dist-packages/pypozyx/structures/byte_structure.py", line 46, in load_hex_string
    byte_data = self.transform_to_bytes()
  File "/usr/local/lib/python2.7/dist-packages/pypozyx/structures/byte_structure.py", line 56, in transform_to_bytes
    return self.transform_data(new_format)
  File "/usr/local/lib/python2.7/dist-packages/pypozyx/structures/byte_structure.py", line 70, in transform_data
    s += struct.pack(self.data_format[i], self.data[i])
**AttributeError: NetworkID instance has no attribute '__trunc__'**

The bug appears only in Python2.7

**Comment by UlixDev** [comment]
It seems the **NetworkID cannot be converted to int so if you implement a **trunc** method that returns the ID the bug is fixed**
I tried on lib installed on my  VM and it worked

**Comment by laurentva** [comment]
Hey Ulisse,

This seems to be a deeper issue regarding single-element data structures in Python 2 that I'm now researching and trying to fix. Going to put it in the next commit with the other fixes.

**Comment by laurentva** [comment]
Fixed.
